// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import analyzer "github.com/rodrigo-brito/gocity/analyzer"
import mock "github.com/stretchr/testify/mock"

// Analyzer is an autogenerated mock type for the Analyzer type
type Analyzer struct {
	mock.Mock
}

// Analyze provides a mock function with given fields:
func (_m *Analyzer) Analyze() (map[string]*analyzer.NodeInfo, error) {
	ret := _m.Called()

	var r0 map[string]*analyzer.NodeInfo
	if rf, ok := ret.Get(0).(func() map[string]*analyzer.NodeInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*analyzer.NodeInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FetchPackage provides a mock function with given fields:
func (_m *Analyzer) FetchPackage() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
