// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: packageName
func (_m *Fetcher) Fetch(packageName string) error {
	ret := _m.Called(packageName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(packageName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
